log_level: info
data: data/data.json
public: public
style_css: assets/style.css
archiveorg:
  creator: Papá Friki
  link: papafriki
  subject:
site:
  author: Papá Friki
  title: Batallitas del día a día de un Papá Friki
  description: Batallitas del día a día de un Papá Friki
  baseurl:
  url: https://atareao.gitlab.io
  avatar: https://assets.gitlab-static.net/uploads/-/system/project/avatar/5685462/avatar.png
  category: Technology
  subcategory: Podcasting
  explicit: true
  email: papafrikipodcast@gmail.com
  gitlab: papafrikipodcast
  rss: http://feeds.feedburner.com/papafriki
  twitter: papa_friki
  google_analytics:
  disqus: papafriki
  youtube: https://www.youtube.com/channel/UCAl-ql8V1IUZKYYLhhUVCYw
  linktree: https://linktr.ee/papa_friki
