log_level: error
creator: Papa Friki
data: /data/rust/aopodcast/data/data.json
public: /data/rust/aopodcast/public
site:
  author: Papá Friki
  name: Papá Friki
  description: Batallitas del día a día de un Papá Friki
  baseurl: /podcast
  avatar: https://assets.gitlab-static.net/uploads/-/system/project/avatar/5685462/avatar.png
  google_analytics:
  disqus: papfriki
  category: Technology
  subcategory: Podcasting
  explicit: true
footer_links:
  dribble:
  email: papafrikipodcast@gmail.com
  facebook:
  flickr:
  gitlab: papafrikipodcast
  instagram:
  linkedin:
  pinterest:
  rss: http://feeds.feedburner.com/papafriki
  twitter: papa_friki
  stackoverflow:
  youtube:
  googleplus:
  telegram:
  archiveorg: papafriki
  mastodon:
  android:
