log_level: info
data: data/data.json
public: public/temporal
style_css: assets/style.css
timezone: Europe/Madrid
archiveorg:
  creator: Papá Friki
  link: papafriki
  subject:
site:
  podcast_feed: feed
  author: Papá Friki
  title: Batallitas del día a día de un Papá Friki
  description: Batallitas del día a día de un Papá Friki
  baseurl: podcast
  url: https://atareao.gitlab.io
  avatar: https://gitlab.com/uploads/-/system/user/avatar/2074936/avatar.png
  category: Technology
  subcategory: Podcasting
  explicit: true
  email: papafrikipodcast@gmail.com
  gitlab: papafrikipodcast
  rss: http://feeds.feedburner.com/papafriki
  twitter: papa_friki
  google_analytics:
  disqus: papafriki
  youtube: https://www.youtube.com/channel/UCAl-ql8V1IUZKYYLhhUVCYw
  linktree: https://linktr.ee/papa_friki
